signup:
  first_name: arya 											
  last_name: stark
  address1: 483 West, 37th street
  address2: #33
  city: New York City
  state: New York
  zip: 10018
  email_facebook: tripthi.testmember19@socialmedialink.com
  pass_facebook: general1234
  email_twitter: tripthi.testmember20@socialmedialink.com
  pass_twitter: general1234
  email_instagram: tripthi.shetty
  pass_instagram: abcd1234
  base_url_facebook: https://facebook.com
  base_url_twitter: https://twitter.com
admin:
  base_url: https://admin-staging.socialmedialink.com/
  email: tripthi.testmember5@socialmedialink.com
  pass: 12345678
member: 
  base_url: https://tripsprint60-staging.socialmedialink.com
  email: arya.stark@yopmail.com
  pass: 12345678
  
  